from django.contrib import admin
from .models import User, Contact, Login,Gallery,PhotoTags,Traveller,FavouriteTours,Employee,TravelAgency,BankAccountDetails,TravelAgent,TourPackage,Activities,Places,TourTags,Hotel,ScheduledOn,Feedback,Booking,Payment,Cancelled,RefundDetails,RecommendedTo

admin.site.register(User)
admin.site.register(Contact)
admin.site.register(Login)
admin.site.register(Gallery)
admin.site.register(PhotoTags)
admin.site.register(Traveller)
admin.site.register(FavouriteTours)
admin.site.register(Employee)
admin.site.register(TravelAgency)
admin.site.register(BankAccountDetails)
admin.site.register(TravelAgent)
admin.site.register(TourPackage)
admin.site.register(Activities)
admin.site.register(Places)
admin.site.register(TourTags)
admin.site.register(Hotel)
admin.site.register(ScheduledOn)
admin.site.register(Feedback)
admin.site.register(Booking)
admin.site.register(Payment)
admin.site.register(Cancelled)
admin.site.register(RefundDetails)
admin.site.register(RecommendedTo)
